In [1]:
import numpy as np

# Создание двух матриц с случайными элементами
matrix1 = np.random.randint(0, 10, size=(3, 3))  # Пример: матрица 3x3 со случайными целыми числами от 0 до 9
matrix2 = np.random.randint(0, 10, size=(3, 3))

# Вывод матриц
print("Матрица 1:")
print(matrix1)
print("\nМатрица 2:")
print(matrix2)

# Поиск одинаковых элементов
common_elements = np.intersect1d(matrix1, matrix2)

if common_elements.size > 0:
    print("\nОбщие элементы в матрицах:")
    print(common_elements)
else:
    print("\nВ матрицах нет общих элементов.")


Матрица 1:
[[0 7 8]
 [6 5 6]
 [4 9 6]]

Матрица 2:
[[3 7 9]
 [0 5 7]
 [5 0 9]]

Общие элементы в матрицах:
[0 5 7 9]
